### ISSUE TITLE
Style the site

### ISSUE THREAD

**Issue by Learner5200** [Learner5200/acebook-MAICers#24]
Make the site look pretty using CSS and possibly Bootstrap.

Ongoing: a good task for when there's nothing else to be getting on with.

**Comment by Learner5200** [comment]
time: LONG, ongoing
priority: MEDIUM-HIGH

**Comment by MHUS25** [comment]
- responsive design
- mobile friendly
- navigation bar with links to parts of the app
- footer information about the application
- clear colour scheme

**Comment by MHUS25** [comment]
We've decided to copy Facebook's colour scheme. Find the relevant hexcodes here: https://www.color-hex.com/color-palette/185
